---
- name: Set up web servers
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Enable/start Apache
      systemd:
        name: apache2
        state: started
        enabled: true
    - name: Deply web content
      template:
        src: ./index.htm.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
